### ISSUE TITLE
SyntaxError: Unexpected token = when running lb

### ISSUE THREAD

**Issue by lnxslck** [strongloop/loopback-cli#63]
# Description/Steps to reproduce

01) npm install -g loopback-cli
02) lb

# Link to reproduction sandbox

$ lb
/usr/local/lib/node_modules/loopback-cli/node_modules/object-assign-deep/objectAssignDeep.js:77
function executeDeepMerge (target, _objects = [], _options = {}) {
                                            ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.module.exports.e.__esModule.default (/usr/local/lib/node_modules/loopback-cli/node_modules/swagger-client/dist/index.js:1:26579)
    at t (/usr/local/lib/node_modules/loopback-cli/node_modules/swagger-client/dist/index.js:1:177)
    at Object.<anonymous> (/usr/local/lib/node_modules/loopback-cli/node_modules/swagger-client/dist/index.js:1:12511)

# Expected result

Present lb command

# Additional information

  node -e 'console.log(process.platform, process.arch, process.versions.node)'
linux x64 4.2.6
  npm ls --prod --depth 0 | grep loopback
├── loopback@3.19.0
├── loopback-boot@2.27.1
├── loopback-component-explorer@6.0.0
├── loopback-connector-remote@3.3.1

**Comment by virkt25** [comment]
@lnxslck this issue is due to a dependency of a dependency in loopback. See https://github.com/swagger-api/swagger-js/issues/1315 for more details. 

Quickest & safest fix - Use Node 6 / 8 / 10

**Comment by lnxslck** [comment]
@virkt25 Thank you so much, that solution worked.
