### ISSUE TITLE
Error: Cannot find module 'ieee754'

### ISSUE THREAD

**Issue by 001123** [strongloop/loopback-cli#65]
Error: Cannot find module 'ieee754'

 at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\kd\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\swagger-client\dist\index.js:7:11355)
    at t (C:\Users\kd\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\swagger-client\dist\index.js:1:177)
    at Object.<anonymous> (C:\Users\kd\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\swagger-client\dist\index.js:7:15)
    at Object.<anonymous> (C:\Users\kd\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\swagger-client\dist\index.js:7:11111)
    at t (C:\Users\kd\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\swagger-client\dist\index.js:1:177)
    at Object.<anonymous> (C:\Users\kd\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\swagger-client\dist\index.js:

**Comment by virkt25** [comment]
connected to https://github.com/strongloop/loopback/issues/3894

Cross posting from strongloop/loopback-next#1367 (comment)

> swagger-api/swagger-js#1326 is the culprit.

**Comment by raymondfeng** [comment]
Fixed by https://github.com/swagger-api/swagger-js/pull/1328
