### ISSUE TITLE
Loopback CLI crashing with type error

### ISSUE THREAD

**Issue by Nop0x** [strongloop/loopback-cli#68]
# Description/Steps to reproduce

I'm trying to create a new model with the CLI. 
The bug came up after I started creating a new LB app inside a directory that already contained an app. I exited out of the app creation process by pressing CTRL-C. After that, the cli keeps crashing no matter what I try to do.

# Link to reproduction sandbox

CLI issue, no sandbox available.

# Expected result

Model creation succeeds.

# Additional information

Stacktrace: 

```
(node:15216) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of undefined
    at C:***\***\***\***\***\node_modules\loopback-cli\node_modules\inquirer\lib\objects\choices.js:16:13
    at Array.map (<anonymous>)
    at new module.exports (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\inquirer\lib\objects\choices.js:15:26)
    at Prompt.module.exports (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\inquirer\lib\prompts\base.js:43:24)
    at new Prompt (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\inquirer\lib\prompts\list.js:26:8)
    at module.exports.PromptUI.fetchAnswer (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\inquirer\lib\ui\prompt.js:77:16)
    at tryCatcher (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\rx\dist\rx.js:63:31)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\rx\dist\rx.js:2140:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\rx\dist\rx.js:1762:31)
    at InnerObserver.tryCatcher (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.next (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\rx\dist\rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\rx\dist\rx.js:1762:31)
    at InnerObserver.next (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\rx\dist\rx.js:3547:65)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\rx\dist\rx.js:1762:31)
    at InnerObserver.tryCatcher (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.next (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\rx\dist\rx.js:5883:51)
(node:15216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:15216) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'type' of undefined
    at C:***\***\***\***\***\node_modules\loopback-cli\node_modules\inquirer\lib\objects\choices.js:16:13
    at Array.map (<anonymous>)
    at new module.exports (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\inquirer\lib\objects\choices.js:15:26)
    at Prompt.module.exports (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\inquirer\lib\prompts\base.js:43:24)
    at new Prompt (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\inquirer\lib\prompts\list.js:26:8)
    at module.exports.PromptUI.fetchAnswer (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\inquirer\lib\ui\prompt.js:77:16)
    at tryCatcher (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\rx\dist\rx.js:63:31)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\rx\dist\rx.js:2140:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\rx\dist\rx.js:1762:31)
    at InnerObserver.tryCatcher (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.next (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\rx\dist\rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\rx\dist\rx.js:1762:31)
    at InnerObserver.next (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\rx\dist\rx.js:3547:65)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\rx\dist\rx.js:1762:31)
    at InnerObserver.tryCatcher (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.next (C:***\***\***\***\***\node_modules\loopback-cli\node_modules\rx\dist\rx.js:5883:51)
```

`node -e 'console.log(process.platform, process.arch, process.versions.node)'` output: 
`win32 x64 8.11.1`

`npm ls --prod --depth 0 | grep loopback` output:
```
+-- @mean-expert/loopback-component-realtime@1.0.1
+-- @mean-expert/loopback-sdk-builder@2.3.1
+-- loopback@3.20.0
+-- loopback-boot@2.27.1
+-- loopback-component-auto-migrate@0.3.1
+-- loopback-component-explorer@6.0.1
+-- loopback-component-passport@3.9.0
+-- loopback-component-passport-custom-user-model@3.8.1-3
+-- loopback-component-storage@3.4.0
+-- loopback-connector-mongodb@3.4.4
+-- loopback-connector-mysql@5.2.0
```

**Comment by dhmlau** [comment]
@Nop0x , i just tried the `lb model` with my Mac and it seems to be working.
I'm using `loopback-cli@4.2.0`.  And my output for `npm ls  --depth 0 | grep loopback` is 
```
├── eslint-config-loopback@8.0.0
├── loopback@3.21.0
├── loopback-boot@2.27.1
├── loopback-component-explorer@6.1.0
```

If you're using the same level of LB node module versions, I can find a windows machine and try again.  Please let me know.  Thanks.

**Comment by dhmlau** [comment]
@Nop0x , are you still having this issue?

**Comment by Nop0x** [comment]
Sorry for the delay, yeah I'm still having this issue. 
Even upgraded my Node version to `8.11.3` to test.

**Comment by Nop0x** [comment]
hey @dhmlau, are there any updates on this?

I tried poking around the CLI a bit more and it seems to be, that my problem is project related. It looks like the CLI is working fine on a fresh project. 

Can you tell me which files the CLI is actually accessing and checking so I can find out where my project problem is?

**Comment by smalesys** [comment]
Hey @Nop0x, did you change the default locations of the config files, like datasources.json or model-config.json, by passing custom paths  in the options of the loopback-boot function?
