### ISSUE TITLE
Continuous errors when running dev server on a fresh install

### ISSUE THREAD

**Issue by aslak01** [strongloop/loopback-cli#82]
Version 3.x installed with loopback-cli (`lb`) as an api-server with no modifications continuously throws errors in Terminal: 

```
Unhandled error for request GET /__webpack_hmr/client: Error: Cannot GET /__webpack_hmr/client
    at raiseUrlNotFoundError (/Users/a/dev/web/loopbackapp/api2/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (/Users/a/dev/web/loopbackapp/api2/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/a/dev/web/loopbackapp/api2/node_modules/express/lib/router/index.js:317:13)
    at /Users/a/dev/web/loopbackapp/api2/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/a/dev/web/loopbackapp/api2/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/a/dev/web/loopbackapp/api2/node_modules/express/lib/router/index.js:275:10)
    at /Users/a/dev/web/loopbackapp/api2/node_modules/express/lib/router/index.js:635:15
    at next (/Users/a/dev/web/loopbackapp/api2/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/Users/a/dev/web/loopbackapp/api2/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/a/dev/web/loopbackapp/api2/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/a/dev/web/loopbackapp/api2/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/a/dev/web/loopbackapp/api2/node_modules/express/lib/router/index.js:317:13)
    at /Users/a/dev/web/loopbackapp/api2/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/a/dev/web/loopbackapp/api2/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/a/dev/web/loopbackapp/api2/node_modules/express/lib/router/index.js:275:10)
    at nosniff (/Users/a/dev/web/loopbackapp/api2/node_modules/dont-sniff-mimetype/index.js:4:5)

```

And so forth. Otherwise the server seems to be running fine, but I don't feel confident to move forward with my project.

**Comment by dhmlau** [comment]
@aslak01, may I know what's the step to reproduce? 

I've tried to scaffold a new app with the following selection and run `npm start` to start the server.  I didn't get any error.
```
$ lb app
? What's the name of your application? test-0131
? Enter name of the directory to contain the project: test-0131
   create test-0131/
     info change the working directory to test-0131

? Which version of LoopBack would you like to use? 3.x (Active Long Term Support)
? What kind of application do you have in mind? api-server (A LoopBack API server with local User auth)
Generating .yo-rc.json
...
```

Looking at the log you provided, `dont-sniff-mimetype` is not one of our dependencies of the generated app.  Did you make other modifications to the app before running?

**Comment by raymondfeng** [comment]
See https://medium.com/@johnstew/webpack-hmr-with-express-app-76ef42dbac17. It seems that you need to add webpack middleware to support that.

**Comment by dhmlau** [comment]
@aslak01 , does the link from @raymondfeng above help?

**Comment by dhmlau** [comment]
@aslak01, do you still encounter this issue?  If not, I'd like to close this ticket. Thanks.

**Comment by mojodev** [comment]
@aslak01 did you find any solution for this issue ??

**Comment by aslak01** [comment]
@dhmlau @mojodev Hey, sorry for the late reply. I haven't been able to test due to time constraints, but I believe @raymondfeng points in the correct direction to solve the issue.

**Comment by dhmlau** [comment]
Thanks @aslak01. Closing as resolved.
